/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Store Rest Api
 * Information about the Store Rest API and how to interact with
 * OpenAPI spec version: 1.0
 */
import type { StoreOrder, StoreTransaction } from '../entities';
import { storeApi } from '../api/storeApi';

export const sellCardAsync = (storeOrder: StoreOrder) => {
  return storeApi<boolean>({
    url: `/api/store/sell`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: storeOrder,
  });
};

export const buyCardAsync = (storeOrder: StoreOrder) => {
  return storeApi<boolean>({
    url: `/api/store/buy`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: storeOrder,
  });
};

export const getCard = () => {
  return storeApi<StoreTransaction[]>({ url: `/api/store`, method: 'get' });
};

export type SellCardAsyncResult = NonNullable<
  Awaited<ReturnType<typeof sellCardAsync>>
>;
export type BuyCardAsyncResult = NonNullable<
  Awaited<ReturnType<typeof buyCardAsync>>
>;
export type GetCardResult = NonNullable<Awaited<ReturnType<typeof getCard>>>;
