/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Store Rest Api
 * Information about the Store Rest API and how to interact with
 * OpenAPI spec version: 1.0
 */
import type { StoreOrder, StoreTransaction } from '../entities';
import { storeApi } from '../api/storeApi';

export const sell = (storeOrder: StoreOrder) => {
  return storeApi<boolean>({
    url: `/api/store/sell`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: storeOrder,
  });
};

export const buy = (storeOrder: StoreOrder) => {
  return storeApi<boolean>({
    url: `/api/store/buy`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: storeOrder,
  });
};

export const getAllTransactions = () => {
  return storeApi<StoreTransaction[]>({ url: `/api/store`, method: 'get' });
};

export type SellResult = NonNullable<Awaited<ReturnType<typeof sell>>>;
export type BuyResult = NonNullable<Awaited<ReturnType<typeof buy>>>;
export type GetAllTransactionsResult = NonNullable<
  Awaited<ReturnType<typeof getAllTransactions>>
>;
