/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */
import type { CardBasicsDTO } from './cardBasicsDTO';

export interface CardDTO {
  attack?: number;
  defence?: number;
  energy?: number;
  hp?: number;
  id?: number;
  userId?: number;
  model?: CardBasicsDTO;
  price?: number;
}
