/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */

export interface CardBasicsDTO {
  description?: string;
  family?: string;
  id?: number;
  imgUrl?: string;
  name?: string;
  smallImgUrl?: string;
}
