/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Card Rest Api
 * Information about the Card Rest API and how to interact with
 * OpenAPI spec version: 1.0
 */

export interface CardBasicsDTO {
  id?: number;
  name?: string;
  description?: string;
  family?: string;
  imgUrl?: string;
  smallImgUrl?: string;
  attackName?: string;
}
