/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Store Rest Api
 * Information about the Store Rest API and how to interact with
 * OpenAPI spec version: 1.0
 */

export type StoreTransactionAction =
  typeof StoreTransactionAction[keyof typeof StoreTransactionAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreTransactionAction = {
  BUY: 'BUY',
  SELL: 'SELL',
} as const;
