/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */
import type { CardDTO } from './cardDTO';

export interface UserDTO {
  account?: number;
  cards?: CardDTO[];
  email?: string;
  id?: number;
  lastName?: string;
  login?: string;
  password?: string;
  surName?: string;
  actionPoints?: number;
}
